title: British Geological Survey
email:
description: >- # this means to ignore newlines until "baseurl:"
  The British Geological Survey is responsible for advising the UK government on geoscience and providing impartial advice to industry, academia and the public.
twitter_username: BritGeoSurvey
github_username: BritishGeologicalSurvey
og_image: "assets/images/GitHub-BGS-socialmedia.png"
minimal_mistakes_skin: default
search: true
breadcrumbs: false
words_per_minute: 180
markdown: kramdown
highlighter: rouge
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: 'Europe/London'
remote_theme: "mmistakes/minimal-mistakes@4.17.2"
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-remote-theme

author:
  name: 'British Geological Survey'
  avatar: '/assets/images/BGS-Icon-Compact-Pos-RGB.svg'
  bio: 'The British Geological Survey is responsible for advising the UK government on geoscience and providing impartial advice to industry, academia and the public.'
  links:
    - label: 'Website'
      icon: 'fas fa-fw fa-link'
      url: 'https://www.bgs.ac.uk'
    - label: 'Twitter'
      icon: 'fab fa-fw fa-twitter-square'
      url: 'https://twitter.com/BritGeoSurvey'
    - label: 'GitHub'
      icon: 'fab fa-fw fa-github'
      url: 'https://github.com/BritishGeologicalSurvey'
    - label: 'Instagram'
      icon: 'fab fa-fw fa-instagram'
      url: 'https://instagram.com/britgeosurvey/'
    - label: 'Facebook'
      icon: 'fab fa-fw fa-facebook'
      url: 'https://www.facebook.com/pages/British-Geological-Survey'
    - label: 'Linkedin'
      icon: 'fab fa-fw fa-linkedin'
      url: 'https://www.linkedin.com/company/british-geological-survey'

footer:
  links:
    - label: 'Website'
      icon: 'fas fa-fw fa-link'
      url: 'https://www.bgs.ac.uk'
    - label: 'Twitter'
      icon: 'fab fa-fw fa-twitter-square'
      url: 'https://twitter.com/BritGeoSurvey'
    - label: 'GitHub'
      icon: 'fab fa-fw fa-github'
      url: 'https://github.com/BritishGeologicalSurvey'
    - label: 'Instagram'
      icon: 'fab fa-fw fa-instagram'
      url: 'https://instagram.com/britgeosurvey/'
    - label: 'Facebook'
      icon: 'fab fa-fw fa-facebook'
      url: 'https://www.facebook.com/pages/British-Geological-Survey'
    - label: 'Linkedin'
      icon: 'fab fa-fw fa-linkedin'
      url: 'https://www.linkedin.com/company/british-geological-survey'

defaults:
  # _posts
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      classes: wide
  # _pages
  - scope:
      path: '_pages'
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

repository: 'BritishGeologicalSurvey/BritishGeologicalSurvey.github.io'

comments:
  provider: 'utterances'
  utterances:
    theme: 'github-light'
    issue_term: 'pathname'
    label: 'comments'

theme: jekyll-theme-minimal

after_footer_scripts:
  - /assets/js/cookie-consent.js

analytics:
  provider: "google"
  google:
    tracking_id: "UA-212008791-1"
    anonymize_ip: false # default